server:
  port: 8202

spring:
  application:
    name: BASE-Server-Test
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8001/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      # 到认证服务器里校验当前请求头中的令牌是否为合法的令牌
      # 通过当前令牌获取对应的用户信息
      user-info-uri: http://localhost:8301/auth/user

feign:
  hystrix:
    # 因为Feign的回退功能是基于Hystrix实现的，所以需要开启它
    enabled: true

hystrix:
  shareSecurityContext: true