server:
  port: 8101

spring:
  application:
    name: BASE-Auth
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: BaseHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/base_cloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8

  redis:
    host: 192.168.56.129
    database: 1
    password: 123456
    port: 6666
    lettuce:
      pool:
        max-active: 2000
        max-wait: 10000
        min-idle: 8
        max-idle: 500
    timeout: 5000

eureka:
  instance:
    # 向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约。这里配置为20秒，即每隔20秒向base-register发送心跳，表明当前服务没有宕机
    lease-renewal-interval-in-seconds: 20
  client:
    # 为true时表示将当前服务注册到Eureak服务端
    register-with-eureka: true
    # 为true时表示从Eureka 服务端获取注册的服务信息
    fetch-registry: true
    # 新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    instance-info-replication-interval-seconds: 30
    # 默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存，这里指定为3秒的原因是方便开发时测试，实际可以指定为默认值即可
    registry-fetch-interval-seconds: 3
    service-url:
      # 指定Eureka服务端地址
      defaultZone: http://admin:123456@localhost:8001/register/eureka/


mybatis-plus:
  # 指定MyBatis XML文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 指定为null，否则再插入空值时会报“无效的列类型”错误
    jdbc-type-for-null: null
  global-config:
    # 设置为false关闭MyBatis Plus Banner打印
    banner: false
